#pragma once

#define ACCEPT "Accept"
// #define ACCEPT_CHARSET "Accept-Charset"
// #define ACCEPT_ENCODING "Accept-Encoding"
// #define ACCEPT_LANGUAGE "Accept-Language"
// #define ACCEPT_RANGES "Accept-Ranges"
// #define ACCESS_CONTROL_ALLOW_ORIGIN "Access-Control-Allow-Origin"
// #define AGE "Age"
// #define ALLOW "Allow"
// #define AUTHORIZATION "Authorization"
// #define CACHE_CONTROL "Cache-Control"
// #define CONNECTION "Connection"
// #define CONTENT_ENCODING "Content-Encoding"
// #define CONTENT_LANGUAGE "Content-Language"
#define CONTENT_LENGTH "Content-Length"
// #define CONTENT_LOCATION "Content-Location"
// #define CONTENT_DISPOSITION "Content-Disposition"
// #define CONTENT_RANGE "Content-Range"
#define CONTENT_TYPE "Content-Type"
// #define DATE "Date"
// #define ETAG "ETag"
// #define EXPECT "Expect"
// #define EXPIRES "Expires"
// #define FROM "From"
// #define HOST "Host"
// #define IF_MATCH "If-Match"
// #define IF_MODIFIED_SINCE "If-Modified-Since"
// #define IF_NONE_MATCH "If-None-Match"
// #define IF_RANGE "If-Range"
// #define IF_UNMODIFIED_SINCE "If-Unmodified-Since"
// #define LAST_MODIFIED "Last-Modified"
#define LOCATION "Location"
// #define MAX_FORWARDS "Max-Forwards"
// #define PRAGMA "Pragma"
// #define PROXY_AUTHENTICATE "Proxy-Authenticate"
// #define PROXY_AUTHORIZATION "Proxy-Authorization"
// #define RANGE "Range"
// #define REFERER "Referer"
// #define RETRY_AFTER "Retry-After"
// #define SERVER "Server"
// #define TE "TE"
// #define TRAILER "Trailer"
// #define TRANSFER_ENCODING "Transfer-Encoding"
// #define UPGRADE "Upgrade"
// #define USER_AGENT "User-Agent"
// #define VARY "Vary"
// #define VIA "Via"
// #define WARNING "Warning"
// #define WWW_AUTHENTICATE "WWW-Authenticate"
